// 店家帳號數據
export const restaurantAccounts = [
  {
    id: "1",
    username: "1",
    password: "1",
    restaurantId: 1,
    restaurantName: "京華樓",
    cuisine: "中式料理",
    description: "正宗北方菜系，提供烤鴨、餃子等經典美食",
    logo: "/placeholder.svg?height=80&width=80&text=京華樓",
  },
  {
    id: "2",
    username: "2",
    password: "2",
    restaurantId: 2,
    restaurantName: "美味漢堡",
    cuisine: "美式料理",
    description: "提供各種美味漢堡、薯條和飲料，道地美式風味",
    logo: "/placeholder.svg?height=80&width=80&text=美味漢堡",
  },
  {
    id: "3",
    username: "3",
    password: "3",
    restaurantId: 3,
    restaurantName: "藤井壽司",
    cuisine: "日式料理",
    description: "新鮮食材直送，正統江戶前壽司體驗",
    logo: "/placeholder.svg?height=80&width=80&text=藤井壽司",
  },
  {
    id: "4",
    username: "4",
    password: "4",
    restaurantId: 4,
    restaurantName: "羅馬廚房",
    cuisine: "義式料理",
    description: "道地義式料理，使用進口食材製作，品味義大利風情",
    logo: "/placeholder.svg?height=80&width=80&text=羅馬廚房",
  },
  {
    id: "5",
    username: "5",
    password: "5",
    restaurantId: 5,
    restaurantName: "泰饗樂",
    cuisine: "泰式料理",
    description: "道地泰國風味，酸辣可口，讓您彷彿置身曼谷",
    logo: "/placeholder.svg?height=80&width=80&text=泰饗樂",
  },
  {
    id: "6",
    username: "6",
    password: "6",
    restaurantId: 6,
    restaurantName: "首爾之星",
    cuisine: "韓式料理",
    description: "正宗韓式烤肉，多種醬料可選，道地韓國風味",
    logo: "/placeholder.svg?height=80&width=80&text=首爾之星",
  },
]
